// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/game_engine/data/event_entity.dart';
import 'features/game_engine/data/game_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 907595932263918476),
    name: 'GameEntity',
    lastPropertyId: const obx_int.IdUid(10, 7486638956266334659),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 737475096414276404),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7589652053019775072),
        name: 'eastPlayer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2975273908801630025),
        name: 'southPlayer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1068399388595588162),
        name: 'westPlayer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5313502419701008441),
        name: 'northPlayer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4853849184206574338),
        name: 'startingPoints',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8628301463649010145),
        name: 'gameLength',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2116136395860185694),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7486638956266334659),
        name: 'endAtZeroPoints',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4008088130924136888),
    name: 'EventEntity',
    lastPropertyId: const obx_int.IdUid(12, 4942640006393107928),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4958936157777069915),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6323374622818562334),
        name: 'gameId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8416254442702912719),
        name: 'index',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7649035335691155758),
        name: 'wind',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2718454775486061211),
        name: 'round',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1973947586645921053),
        name: 'honba',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1935826849028341886),
        name: 'endType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4549540325991033019),
        name: 'winnerJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3835434909280447315),
        name: 'loser',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 850113673712173560),
        name: 'tenpai',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6764285853156245033),
        name: 'riichiDeclarers',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4942640006393107928),
        name: 'chonbo',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4008088130924136888),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [1019572773752152822],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    GameEntity: obx_int.EntityDefinition<GameEntity>(
      model: _entities[0],
      toOneRelations: (GameEntity object) => [],
      toManyRelations: (GameEntity object) => {},
      getId: (GameEntity object) => object.id,
      setId: (GameEntity object, int id) {
        object.id = id;
      },
      objectToFB: (GameEntity object, fb.Builder fbb) {
        final eastPlayerOffset = fbb.writeString(object.eastPlayer);
        final southPlayerOffset = fbb.writeString(object.southPlayer);
        final westPlayerOffset = fbb.writeString(object.westPlayer);
        final northPlayerOffset = fbb.writeString(object.northPlayer);
        final gameLengthOffset = fbb.writeString(object.gameLength);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, eastPlayerOffset);
        fbb.addOffset(2, southPlayerOffset);
        fbb.addOffset(3, westPlayerOffset);
        fbb.addOffset(4, northPlayerOffset);
        fbb.addInt64(5, object.startingPoints);
        fbb.addOffset(6, gameLengthOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(9, object.endAtZeroPoints);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final eastPlayerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final southPlayerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final westPlayerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final northPlayerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final startingPointsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final gameLengthParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final endAtZeroPointsParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = GameEntity(
          id: idParam,
          eastPlayer: eastPlayerParam,
          southPlayer: southPlayerParam,
          westPlayer: westPlayerParam,
          northPlayer: northPlayerParam,
          startingPoints: startingPointsParam,
          gameLength: gameLengthParam,
          endAtZeroPoints: endAtZeroPointsParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    EventEntity: obx_int.EntityDefinition<EventEntity>(
      model: _entities[1],
      toOneRelations: (EventEntity object) => [],
      toManyRelations: (EventEntity object) => {},
      getId: (EventEntity object) => object.id,
      setId: (EventEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EventEntity object, fb.Builder fbb) {
        final windOffset = fbb.writeString(object.wind);
        final endTypeOffset = fbb.writeString(object.endType);
        final winnerJsonOffset = fbb.writeString(object.winnerJson);
        final loserOffset = object.loser == null
            ? null
            : fbb.writeString(object.loser!);
        final tenpaiOffset = fbb.writeList(
          object.tenpai.map(fbb.writeString).toList(growable: false),
        );
        final riichiDeclarersOffset = fbb.writeList(
          object.riichiDeclarers.map(fbb.writeString).toList(growable: false),
        );
        final chonboOffset = fbb.writeList(
          object.chonbo.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.gameId);
        fbb.addInt64(2, object.index);
        fbb.addOffset(3, windOffset);
        fbb.addInt64(4, object.round);
        fbb.addInt64(5, object.honba);
        fbb.addOffset(6, endTypeOffset);
        fbb.addOffset(7, winnerJsonOffset);
        fbb.addOffset(8, loserOffset);
        fbb.addOffset(9, tenpaiOffset);
        fbb.addOffset(10, riichiDeclarersOffset);
        fbb.addOffset(11, chonboOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final gameIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final indexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final windParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final roundParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final honbaParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final endTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final winnerJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final loserParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final tenpaiParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final riichiDeclarersParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 24, []);
        final chonboParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final object = EventEntity(
          id: idParam,
          gameId: gameIdParam,
          index: indexParam,
          wind: windParam,
          round: roundParam,
          honba: honbaParam,
          endType: endTypeParam,
          winnerJson: winnerJsonParam,
          loser: loserParam,
          tenpai: tenpaiParam,
          riichiDeclarers: riichiDeclarersParam,
          chonbo: chonboParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GameEntity] entity fields to define ObjectBox queries.
class GameEntity_ {
  /// See [GameEntity.id].
  static final id = obx.QueryIntegerProperty<GameEntity>(
    _entities[0].properties[0],
  );

  /// See [GameEntity.eastPlayer].
  static final eastPlayer = obx.QueryStringProperty<GameEntity>(
    _entities[0].properties[1],
  );

  /// See [GameEntity.southPlayer].
  static final southPlayer = obx.QueryStringProperty<GameEntity>(
    _entities[0].properties[2],
  );

  /// See [GameEntity.westPlayer].
  static final westPlayer = obx.QueryStringProperty<GameEntity>(
    _entities[0].properties[3],
  );

  /// See [GameEntity.northPlayer].
  static final northPlayer = obx.QueryStringProperty<GameEntity>(
    _entities[0].properties[4],
  );

  /// See [GameEntity.startingPoints].
  static final startingPoints = obx.QueryIntegerProperty<GameEntity>(
    _entities[0].properties[5],
  );

  /// See [GameEntity.gameLength].
  static final gameLength = obx.QueryStringProperty<GameEntity>(
    _entities[0].properties[6],
  );

  /// See [GameEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<GameEntity>(
    _entities[0].properties[7],
  );

  /// See [GameEntity.endAtZeroPoints].
  static final endAtZeroPoints = obx.QueryBooleanProperty<GameEntity>(
    _entities[0].properties[8],
  );
}

/// [EventEntity] entity fields to define ObjectBox queries.
class EventEntity_ {
  /// See [EventEntity.id].
  static final id = obx.QueryIntegerProperty<EventEntity>(
    _entities[1].properties[0],
  );

  /// See [EventEntity.gameId].
  static final gameId = obx.QueryIntegerProperty<EventEntity>(
    _entities[1].properties[1],
  );

  /// See [EventEntity.index].
  static final index = obx.QueryIntegerProperty<EventEntity>(
    _entities[1].properties[2],
  );

  /// See [EventEntity.wind].
  static final wind = obx.QueryStringProperty<EventEntity>(
    _entities[1].properties[3],
  );

  /// See [EventEntity.round].
  static final round = obx.QueryIntegerProperty<EventEntity>(
    _entities[1].properties[4],
  );

  /// See [EventEntity.honba].
  static final honba = obx.QueryIntegerProperty<EventEntity>(
    _entities[1].properties[5],
  );

  /// See [EventEntity.endType].
  static final endType = obx.QueryStringProperty<EventEntity>(
    _entities[1].properties[6],
  );

  /// See [EventEntity.winnerJson].
  static final winnerJson = obx.QueryStringProperty<EventEntity>(
    _entities[1].properties[7],
  );

  /// See [EventEntity.loser].
  static final loser = obx.QueryStringProperty<EventEntity>(
    _entities[1].properties[8],
  );

  /// See [EventEntity.tenpai].
  static final tenpai = obx.QueryStringVectorProperty<EventEntity>(
    _entities[1].properties[9],
  );

  /// See [EventEntity.riichiDeclarers].
  static final riichiDeclarers = obx.QueryStringVectorProperty<EventEntity>(
    _entities[1].properties[10],
  );

  /// See [EventEntity.chonbo].
  static final chonbo = obx.QueryStringVectorProperty<EventEntity>(
    _entities[1].properties[11],
  );
}
